### PR TITLE
Implement Cookies , Visual Player state

### PR DESCRIPTION
**Pull request by weidi**
Implemented Cookies to save Autoplay and random playback state,
Add visual feedback for Player state

### CODE REVIEW

**Comment by andygruber** [comment]
@weidi 
Very nice addition, however, can you please separate the visual changes from the cookie addition? Reason is, that I think the usage of cookies needs to add also a cookie banner asking for permission to use cookies. I don´t think the cookie part can be merged like that for this reason. But the GUI changes are ready.

**Comment by weidi** [comment]
The great thing is that we checked with the law and you don't have to have a cookie banner for technical only Cookies so no problem here.

**Comment by andygruber** [comment]
> The great thing is that we checked with the law and you don't have to have a cookie banner for technical only Cookies so no problem here.

Can you please reference that information here?

In general I very much prefer to to have self contained pull requests, instead of mixing multiple topics into one PR.

**Comment by weidi** [comment]
> > The great thing is that we checked with the law and you don't have to have a cookie banner for technical only Cookies so no problem here.
> 
> Can you please reference that information here?
> 
> In general I very much prefer to to have self contained pull requests, instead of mixing multiple topics into one PR.

Absolutely with you and yes mixed two things here.

Here is the link: 

https://europa.eu/youreurope/business/dealing-with-customers/data-protection/online-privacy/index_en.htm

As those cookies are not to identify users there is no problem with them.

**Pull request merged**
